version: "3"
services:
  app:
    build: .
    environment:
      - REDIS_URL=redis://redis
    links:
      - redis
    network_mode: bridge
  redis:
    image: redis:6.0-alpine
    network_mode: bridge
