version: "3"
services:
  app:
    environment:
      - PORT
    ports:
      - $PORT:$PORT
    volumes:
      - /app/node_modules
  redis:
    ports:
      - 6379:6379
  sql:
    ports:
      - 5432:5432
